// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncrawbfwwpdgyictjgje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcmF3YmZ3d3BkZ3lpY3RqZ2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODE0OTYsImV4cCI6MjA2MDA1NzQ5Nn0.mx-yUB_C9Q-d2mJ4ZwfvAY80dtMl2omWkaYAMdNRh9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);